# Generated by Django 3.2.7 on 2021-12-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField(null=True)),
                ('icon', models.ImageField(upload_to='program_icons')),
                ('pinned_to_desktop', models.BooleanField(default=True)),
                ('pinned_to_startmenu', models.BooleanField(default=False)),
                ('pinned_to_toolbar', models.BooleanField(default=False)),
                ('desktop_icon_position', models.CharField(max_length=10)),
                ('startmenu_icon_size', models.IntegerField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
            ],
        ),
    ]
