# Generated by Django 3.2 on 2022-02-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagif', '0003_person_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(default=None, null=True, upload_to='instagif/image/'),
        ),
    ]
